apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
  name: planetarium-service-monitor
  labels:
    app: planetarium

spec:
  jobLabel: app
  selector:
    matchLabels:
      app: planetarium
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s