apiVersion: v1

kind: ServiceMonitor

metadata:
  name: service-monitor
  labels:
    app: service-monitor

spec:
  jobLabel: app
  selector:
    matchLabels:
      app: planetarium-clusterip
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 10s